kreshuklab/plant-seg

plantseg/__init__.py
plantseg/gui/__init__.py
plantseg/gui/gui_tools.py
plantseg/gui/gui_widgets.py
plantseg/gui/plantsegapp.py
plantseg/pipeline/__init__.py
plantseg/pipeline/steps.py
plantseg/pipeline/utils.py
plantseg/predictions/utils.py
plantseg/resources/gui_configuration.yaml
plantseg/resources/models_zoo.yaml
plantseg/run_plantseg.py

Add gui functionality

---

.bumpversion.cfg
.travis.yml
README.md
conda-recipe/README.md
examples/config.yaml
plantseg/predictions/utils.py

Fixes https://github.com/hci-unihd/plant-seg/issues/23

Add Travis CI config. Add Unet2D support

---

plantseg/predictions/utils.py

Add missing config options and validation for 2D Unet prediction to work correctly

Fix 2D Unet configuration

---

.travis.yml

Build and push a docker image to the docker registry (https://hub.docker.com/repository/docker/wolny/plantseg) automatically when a new tag is created

Add docker build and docker push to travis.yml

---

evaluation/evaluation_segmentation_mesh.py

add evaluation script for "binary PLY" surface meshes

Mesh evaluation

---

plantseg/dataprocessing/dataprocessing.py
plantseg/pipeline/raw2seg.py
tests/test_data_processing.py

Fixes https://github.com/hci-unihd/plant-seg/issues/55

Add crop_volume option to pre-processing

---

README.md
evaluation/lmc_eval.py
plantseg/pipeline/raw2seg.py
plantseg/pipeline/steps.py
plantseg/pipeline/utils.py
plantseg/resources/lifted_multicut_example.yaml
plantseg/resources/nuclei_predictions_example.yaml
plantseg/segmentation/lmc.py
plantseg/segmentation/utils.py

Add LiftedMulticut to the list of available algorithms

---

MANIFEST.in
examples/config.yaml
plantseg/gui/gui_tools.py
plantseg/gui/gui_widgets.py
plantseg/pipeline/__init__.py
plantseg/pipeline/config_validation.py
plantseg/pipeline/raw2seg.py
plantseg/predictions/predict.py
plantseg/predictions/utils.py
plantseg/resources/config_gui_template.yaml
plantseg/resources/raw2seg_template.yaml
tests/resources/test_config.yaml

Config validation from template
- @wolny  if a field is miss-configured we can set up fall backs, but we need to decide which one
- Do we need more tests? 
- fixes https://github.com/hci-unihd/plant-seg/issues/40
- fixes https://github.com/hci-unihd/plant-seg/issues/46
- fixes https://github.com/hci-unihd/plant-seg/issues/65
- fixes https://github.com/hci-unihd/plant-seg/issues/62
-  fixes https://github.com/hci-unihd/plant-seg/issues/30

Config validation

---

.travis.yml
conda-recipe/meta.yaml
plantseg/predictions/predict.py
plantseg/segmentation/multicut.py

- fix conda recipe
- minor bug in patch size validation

Fix conda recipe

---

plantseg/pipeline/config_validation.py
plantseg/resources/raw2seg_template.yaml

implements:
- if key is missing then check for defaults. only if defaults fails then fail.
- if an extra key is present plantseg fail

Relax validation

---

plantseg/predictions/utils.py
plantseg/resources/config_gui_template.yaml
plantseg/resources/config_predict_template.yaml
plantseg/resources/lifted_multicut_example.yaml
plantseg/resources/raw2seg_template.yaml
tests/resources/test_config.yaml

Fixes: https://github.com/hci-unihd/plant-seg/issues/82

Allow patch halo configuration 

---

plantseg/pipeline/steps.py
plantseg/segmentation/lmc.py

fix bug in lmc

---

conda-recipe/meta.yaml
plantseg/segmentation/dtws.py
plantseg/segmentation/gasp.py
plantseg/segmentation/lmc.py
plantseg/segmentation/multicut.py

Homogenize super pixel implementation for all workflows

---

plantseg/viewer/containers.py
plantseg/viewer/dag_handler.py
plantseg/viewer/headless.py
plantseg/viewer/logging.py
plantseg/viewer/viewer.py
plantseg/viewer/widget/dataprocessing.py
plantseg/viewer/widget/io.py
plantseg/viewer/widget/predictions.py
plantseg/viewer/widget/proofreading/proofreading.py
plantseg/viewer/widget/proofreading/split_merge_tools.py
plantseg/viewer/widget/segmentation.py
plantseg/viewer/widget/utils.py

This branch:
- Cleanup and polish the proofreading tool
- Adds a correct labels mask that can be used to export and protect the cell that the user marks as correct. To mark a cell as correct is enough to double-click on it. One can double-click a second time to remove the cell from the correct mask.

Improved proofreading

---

.github/workflows/build-deploy-on-conda.yml
README.md
conda-recipe/README.md
conda-recipe/meta.yaml
deployment/win/construct.yaml
deployment/win_workaround/make_bin.bat
environment.yaml
examples/config.yaml
plantseg/augment/transforms.py
plantseg/io/h5.py
plantseg/legacy_gui/gui_widgets.py
plantseg/pipeline/config_validation.py
plantseg/pipeline/raw2seg.py
plantseg/predictions/functional/array_dataset.py
plantseg/predictions/functional/array_predictor.py
plantseg/predictions/functional/predictions.py
plantseg/predictions/functional/slice_builder.py
plantseg/predictions/functional/utils.py
plantseg/predictions/predict.py
plantseg/resources/config_gui_template.yaml
plantseg/resources/config_predict_template.yaml
plantseg/resources/models_zoo.yaml
plantseg/resources/raw2seg_template.yaml
plantseg/segmentation/dtws.py
plantseg/utils.py
plantseg/viewer/widget/predictions.py
tests/resources/test_config.yaml

Remove pytorch-3dunet dependency

---

README.md
plantseg/predictions/functional/array_predictor.py
plantseg/predictions/functional/predictions.py
plantseg/predictions/functional/utils.py
plantseg/predictions/predict.py
plantseg/viewer/widget/predictions.py

Improve batch_size selection

---

plantseg/io/zarr.py
tests/test_io_zarr.py

PR to resolve [issue](https://github.com/hci-unihd/plant-seg/issues/143#issue-1664511616) for reading and writing zarrs.

Read write zarrs

---

conda-recipe/meta.yaml
environment.yaml
plantseg/io/__init__.py
plantseg/io/h5.py
plantseg/io/io.py
plantseg/io/zarr.py
plantseg/legacy_gui/gui_tools.py
plantseg/pipeline/utils.py
plantseg/utils.py
plantseg/viewer/widget/dataprocessing.py
plantseg/viewer/widget/io.py
plantseg/viewer/widget/predictions.py
plantseg/viewer/widget/proofreading/proofreading.py
plantseg/viewer/widget/utils.py
tests/conftest.py
tests/test_io_zarr.py

Add zarr support

---

environment-dev.yaml
examples/config_advanced.yaml
plantseg/dataprocessing/functional/dataprocessing.py
plantseg/legacy_gui/gui_widgets.py
plantseg/legacy_gui/plantsegapp.py
plantseg/pipeline/raw2seg.py
plantseg/predictions/functional/predictions.py
plantseg/resources/config_gui_template.yaml
plantseg/viewer/containers.py
plantseg/viewer/widget/predictions.py
plantseg/viewer/widget/utils.py

This PR attempts to fix:
- #173 
For multi-channel UNets, return each channel of the prediction as a layer in Napari. I made minimal changes to detect and handle multi-channel output in `unet_predictions()`, `start_prediction_threading_process()` and `widget_unet_predictions()`.
Figure 1: an overlay of segmentation + boundary pred from multi-channel output + raw
1. Add key and channel selection in all steps for GUI pipeline
2. Add LiftedMulticut (LMC) in GUI pipeline's segmentation frame, and add path/key/channel selection in it
3. Add key and channel default values in GUI config template
Figure 2: Key/channel selection for all steps and new LMC interface
1. Tk GUI only allows fixed-typed entries. As a result, `None` key and `None` values has to be `"None"` string and `-1` integer …

Fix Flow in GUI & Napari: key, channel, LMC in GUI; multi-channel UNet layers in Napari

---

.github/workflows/build-deploy-book.yml
README.md
docs/chapters/getting_started/quick_start.md
docs/chapters/plantseg_classic_cli/index.md
docs/chapters/plantseg_classic_gui/segmentation.md

This should fix:
- #187 
This is related to 
- #177 
Since Kay is asking about the disabled Wiki pages of PlantSeg, I now create a PR and merge it without asking for a review.

Redirect all Wiki links to new doc and improve READMEs

---

plantseg/utils.py
plantseg/viewer/widget/predictions.py

Some of my custom models are causing problems, I guess this option helps users who knows their models and wants to avoid problems.

Add option to only run official models in "Try all Available Models"

---

plantseg/viewer/containers.py
plantseg/viewer/headless.py
plantseg/viewer/widget/io.py

- fix #173 
- extend channel selection to h5/zarr
-  streamline open widget (remove advance load and simplify layout selection) 
- add manual slicing 
- fix unrelated dask bug

extend channel selection

---

plantseg/legacy_gui/gui_tools.py
plantseg/pipeline/raw2seg.py
plantseg/predictions/functional/array_predictor.py
plantseg/predictions/predict.py
plantseg/utils.py

Since v1.6.6, I stopped testing Legacy GUI and depend purely on passing `pytest` for this interface. But it seems there are not enough tests for this. I fixed:
1. Problems caused by moving `os` to `pathlib`
2. Problems caused by re-introducing halo and fix halo/padding implementation
3. Problems caused by forcing `tuple` type for fixed-length sequences
This should fix #236

Fix Legacy GUI after v1.7.0

---

plantseg/dataprocessing/dataprocessing.py
plantseg/dataprocessing/functional/dataprocessing.py
plantseg/dataprocessing/functional/labelprocessing.py
plantseg/io/h5.py
plantseg/io/io.py
plantseg/io/pil.py
plantseg/io/tiff.py
plantseg/io/zarr.py
plantseg/models/zoo.py
plantseg/predictions/functional/array_dataset.py
plantseg/predictions/functional/predictions.py
plantseg/predictions/functional/utils.py
plantseg/predictions/predict.py
plantseg/run_plantseg.py
plantseg/segmentation/functional/segmentation.py
plantseg/training/model.py
plantseg/utils.py
plantseg/viewer/headless.py
plantseg/viewer/widget/dataprocessing.py
plantseg/viewer/widget/predictions.py
tests/conftest.py
tests/test_data_processing.py
tests/test_io_zarr.py
tests/test_model.py
tests/test_model_zoo.py

While working on these two features, I discovered bugs along the way. The process turned out to be complex and entangled, so I decided to include everything in a single PR.

Fix `CYX`/`CZYX` pad/halo, fix `io.zarr`/tests, fix typing, refactor model load

---

.github/workflows/build-deploy-book.yml
.github/workflows/build-deploy-on-conda.yml
environment-dev.yaml
plantseg/dataprocessing/functional/dataprocessing.py
plantseg/viewer/containers.py
plantseg/viewer/widget/dataprocessing.py
plantseg/viewer/widget/utils.py
tests/test_widget_preprocessing.py

This PR:
- originally attempts to create tests for #249, as the first set of tests for PlantSeg Napari
- starts to look into #253, by adding a complete set of tests for image rescaling widget in Napari GUI
- updates pre-processing module for consistent step and layer names
- starts to use Black/Ruff

Tests for rescaling widget

---

plantseg/viewer/widget/dataprocessing.py

(Miss-clicked sync icon when I wanted to click `master` to create a new branch, so 29a47c811ec5c82e3a0fe5c41bdd4f1c694478a1 was pushed to master before I finish this PR. Let's protect `master`? @lorenzocerrone)
Fixed the following:
- Use `RangeSlider` instead of `FloatRangeSlider` for #278
- Now type annotation `tuple[int, int]` will actually make the tuple `int`s, no need to convert, and
- Therefore `crop_z.value :: tuple[int, int]` no longer accept e.g. `crop_z.value[1] = `.
- Handle `None` image when all images deleted
Full `diff` between 158bc0174a026bb2df395e09577964b3277ea760 and d1448e603795a3473bc470f1033f50adb35619ec
<details>
<summary>Difference</summary>
</details>

fix(cropping): use RangeSlider to fix #278 | handle `None` image

---

plantseg/__init__.py
plantseg/functionals/dataprocessing/__init__.py
plantseg/functionals/dataprocessing/advanced_dataprocessing.py
plantseg/functionals/proofreading/split_merge_tools.py
plantseg/loggers.py
plantseg/models/zoo.py
plantseg/tasks/dataprocessing_tasks.py
plantseg/viewer_napari/__init__.py
plantseg/viewer_napari/containers.py
plantseg/viewer_napari/loggers.py
plantseg/viewer_napari/logging.py
plantseg/viewer_napari/viewer.py
plantseg/viewer_napari/widgets/__init__.py
plantseg/viewer_napari/widgets/dataprocessing.py
plantseg/viewer_napari/widgets/io.py
plantseg/viewer_napari/widgets/predictions.py
plantseg/viewer_napari/widgets/proofreading.py
plantseg/viewer_napari/widgets/segmentation.py
plantseg/viewer_napari/widgets/utils.py

1. "Add Custom Model" widget.
2. "Remove False Positive" widget.
3. For GUI (Napari), use one logger with widget/thread name, following convention in V1.
4. For all other parts, use module level loggers with "root" logger `plantseg.` customised.
5. Do no use `label`, `labels`, or `_label(s)` as widget argument names.

Add important widgets and improve logger further

---

.github/workflows/build-deploy-on-conda.yml
.gitignore

Codecov is now used in PlantSeg.

Use Codecov

---

plantseg/viewer_napari/widgets/io.py

In this PR, I attempted to fix #282. 
Printing in `_on_done()` does take effect, but keys are not reassigned. As a temporary fix, a button for refreshing the key list is added.

fix(widget-IO): temp fix #282 and auto generate layer name

---

.github/workflows/build-deploy-book.yml
docs/chapters/getting_started/troubleshooting.md
plantseg/legacy_gui/plantsegapp.py

Although I'm about to merge v2 branch, I believe there will be users trying to install an older version. 
Here I finish this change in v1 documentation.

Record issue missing button

---

plantseg/viewer_napari/containers.py
plantseg/viewer_napari/viewer.py
plantseg/viewer_napari/widgets/dataprocessing.py
plantseg/viewer_napari/widgets/io.py
plantseg/viewer_napari/widgets/prediction.py
plantseg/viewer_napari/widgets/segmentation.py

Updated tab/widget names and rearranged their order to ensure a more logical, step-by-step user experience in the GUI.

refactor(GUI): rename and reorder widgets for intuitive sequential flow

---

.gitignore
plantseg/viewer_napari/widgets/dataprocessing.py
plantseg/viewer_napari/widgets/io.py
plantseg/viewer_napari/widgets/prediction.py
plantseg/viewer_napari/widgets/proofreading.py
plantseg/viewer_napari/widgets/segmentation.py
plantseg/viewer_napari/widgets/utils.py
tests/functionals/prediction/test_size_finder.py

This PR: 
- Drastically improve segmentation performance on apple silicon Mac
- Does not address bad CNN inference

Fix perfomance on mac

---

.github/workflows/build-and-publish-docs.yml
.github/workflows/build-and-test-package.yml

Fix `anaconda_telemetry` error in CI

---

plantseg/functionals/dataprocessing/advanced_dataprocessing.py
plantseg/tasks/dataprocessing_tasks.py
plantseg/viewer_napari/widgets/dataprocessing.py
plantseg/viewer_napari/widgets/utils.py
tests/conftest.py
tests/functionals/dataprocessing/test_advanced.py
tests/tasks/dataprocessing/test_advanced_dataprocessing_tasks.py
tests/widgets/test_widget_nuc_fix.py

- Fix the "quantile" parameters not normalised into percentage
- Add tests for nuc-fix functional/task/widget
- Test for widget that wraps scheduler will hang

Add tests for and fix nuclei-assisted post-processing

---

.github/workflows/build-and-publish-docs.yml
.github/workflows/build-and-test-package.yml

Use older ubuntu runner in CI

---

plantseg/functionals/prediction/prediction.py
plantseg/functionals/prediction/utils/array_predictor.py
plantseg/tasks/prediction_tasks.py
plantseg/viewer_napari/widgets/prediction.py
plantseg/viewer_napari/widgets/utils.py
pyproject.toml

Shows progress bar in napari.
All tasks show a spinner in the bottom-right corner, additionally, the unet prediction shows a more detailed progress bar in the widget.
fixes #395

Progress bar

---

plantseg/viewer_napari/viewer.py

The default napari splash screen suggests drag-and-drop to load an image, which is not supported in plantseg.
This PR replaces the napari welcome message with a more fitting one.

Better splash screen

---

.github/workflows/release.yml

fix: set prerelease on prereleases

---

plantseg/viewer_napari/viewer.py
plantseg/viewer_napari/widgets/segmentation.py

Support small/low resolution screens.
Makes the docked widgets scrollable up/down and left/right (both only if necessary).

feat: make gui scrollable

---

plantseg/utils.py
plantseg/viewer_napari/viewer.py
tests/utils/test_utils.py

fix: napari dock properly behaving

---

conda-recipe/meta.yaml
constructor/unix_installer.sh
constructor/win_installer.bat
docs/chapters/getting_started/installation.md
plantseg/viewer_napari/updater.py
plantseg/viewer_napari/viewer.py
plantseg/viewer_napari/widgets/proofreading.py

The installer build during CI created a plantseg package plantseg, the CI on conda-forge one called plant-seg. Unified name: plant-seg
Prerequisit for #453

feat: in-app plantseg updates

---

plantseg/viewer_napari/widgets/input.py
tests/widgets/test_input.py

* Key refresh button on input page now in-line with key selection
* Key selection chooses input type if possible
* Changing the file updates the layer name

chore: inline refresh button

---

plantseg/tasks/segmentation_tasks.py
plantseg/viewer_napari/viewer.py
plantseg/viewer_napari/widgets/segmentation.py
tests/tasks/test_segmentation_tasks.py
tests/widgets/test_segmentation.py

By default, the watershed and agglomeration are now one step. An advanced view is available with additional options exposed.

feat: two-step segmentation

---

plantseg/workflow_gui/editor.py
plantseg/workflow_gui/widgets.py

* Tasks hidden behind `advanced view` button.
* Option reordered

feat: improved workflow editor
