kreshuklab/plant-seg

- plantseg/dataprocessing/dataprocessing.py
- plantseg/gui/gui_widgets.py
- plantseg/pipeline/raw2seg.py
- plantseg/pipeline/steps.py
- plantseg/resources/config_gui_template.yaml
> Allow saving raw data in the post-processing step

- conda-recipe/meta.yaml
hack gasp into install with pip in order to bypass windows build requirements
> Fix meta windows

- bioimage-io/UNet2DArabidopsisOvules.model/UNet2DArabidopsisOvules.model.yaml
- bioimage-io/UNet3DArabidopsisOvules.model/UNet3DArabidopsisOvules.model.yaml
- bioimage-io/UNet3DLateralRoot.model/UNet3DLateralRoot.model.yaml
- bioimage-io/UNet3DLateralRootNuclei.model/UNet3DLateralRootNuclei.model.yaml
it seems to be necessary to specify the link to the source file without the leading `./`, at least currently. In principle this should be supported, too, but for now it's easier to fix the models.
> correct link to local model file

- plantseg/pipeline/config_validation.py
- plantseg/predictions/utils.py
A small PR that add the functionality to run predictions from path and not only by "name".
This should make no difference for normal plantseg user, but makes way easier to script hyperparamers search. 
example:
```
cnn_prediction:
...
model_name: /home/user/experiment/new_model/
...
```
Of course plantseg will check if all files are in the directory and raise and error if the files are not there.
> run plant seg by specifing a dir path

- plantseg/dataprocessing/dataprocessing.py
- plantseg/gui/gui_tools.py
- plantseg/pipeline/raw2seg.py
- plantseg/pipeline/steps.py
- plantseg/pipeline/utils.py
> Fix CNN prediction rescaling

- plantseg/resources/models_zoo.yaml
fixes: https://github.com/hci-unihd/plant-seg/issues/138
> Fix incorrect model weights on Zenodo

- plantseg/resources/models_zoo.yaml
- plantseg/run_plantseg.py
- plantseg/utils.py
- plantseg/viewer/headless.py
- plantseg/viewer/widget/dataprocessing.py
- plantseg/viewer/widget/io.py
- plantseg/viewer/widget/predictions.py
- plantseg/viewer/widget/proofreading/proofreading.py
- plantseg/viewer/widget/segmentation.py
- plantseg/viewer/widget/utils.py
> Add nice widgets callbacks

- plantseg/resources/models_zoo.yaml
Added the new generic plant nuclei 3D UNet model, `generic_plant_nuclei_3D`, as a built-in model for PlantSeg. 
@wolny I tested it with command line raw2seg pipeline and PlantSeg downloaded the weights and config during inference step. Should be ready to merge. I noticed you only put `nuclei` for your _nucleus boundaries + body_ networks; I guess I'll just leave it for you and Lorenzo to update all at once in the future.
PS: I usually avoid touching the formatting etc. But this file was using a mixed style: `[0.25, 0.1625, 0.1625]` and `[ 80, 160, 160 ]`, so I didn't bother to change it back when it got autoformatted.
> Add Zenodo record for generic plant nuclei model

- README.md
- plantseg/__init__.py
Hi,
I would like to make the PlantSeg home directory configurable and added the option to set the `PLANTSEG_HOME` environment variable. 
Cheers
> Add option to set home_path via PLANTSEG_HOME env-variable.

- plantseg/resources/models_zoo.yaml
- to fix #192 
Hey @lorenzocerrone @wolny, do you think we can have alias for models? Our new nuclear model is named as PlantSeg_3Dnuc_platinum in the paper, but it doesn't really fit into the zoo and it's not even clear that it's a nuclear model.
> Rename generic plant nuclear model for paper submission

- plantseg/dataprocessing/functional/advanced_dataprocessing.py
- plantseg/segmentation/functional/segmentation.py
- plantseg/segmentation/gasp.py
- plantseg/viewer/containers.py
- plantseg/viewer/widget/predictions.py
- plantseg/viewer/widget/segmentation.py
Instead of adding an option to each "boundary -> segmentation" algorithm as discussed in #174, I made a separate widget for Napari GUI pipeline for generic usage. This independent design avoids bundled computation within other functions such as GASP, allows easy trial-and-error strategy, accepts flexible input pmaps/images and threshold, and is useful in unexpected use cases.
I came up with three designs and decided to implement only one. I now add this to Napari, and will think about the best way to do it in the other UI. 
1. **Method 1:** Threshold foreground to a binary mask and multiply with the segmentation pixel-wise ❌
1. **Pros:** very fast; false positive parts will be deleted within objects if foreground quality is high
2. **Cons:** depending on the quality of foreground …
> Add widget: remove objects using a probability map

- plantseg/augment/transforms.py
- plantseg/predictions/functional/predictions.py
680c73cec061a2b5d7178d97f753f8d2de2b268a is not necessary.
> Fix Tiling Artefact: intensity normalisation was correct

- docs/chapters/getting_started/contributing.md
- environment-dev.yaml
1. Use `cuda-version=12.3` to avoid `mamba` adding `cudatoolkit` (11.1) into the environment, fix #228 
2. Add bioimageio.core to dev environment to allow alternative inference engine. PlantSeg inference and bioimageio.core inference are separately and successfully tested.
> Dev Env: Add BioImage.IO Core dependency and fix CUDA installation

- docs/chapters/python_api/cnn_predictions.md
- docs/chapters/python_api/segmentation.md
- plantseg/dataprocessing/dataprocessing.py
- plantseg/dataprocessing/functional/advanced_dataprocessing.py
- plantseg/dataprocessing/functional/dataprocessing.py
- plantseg/dataprocessing/functional/labelprocessing.py
- plantseg/io/h5.py
- plantseg/io/tiff.py
- plantseg/io/zarr.py
- plantseg/predictions/functional/predictions.py
- plantseg/segmentation/functional/segmentation.py
Interestingly, `np.ndarray` has been used correctly in a few docstrings whose functions are using `np.array`.
> Type Fix: `np.array` is not a type, change to `np.ndarray`

- docs/chapters/getting_started/installation.md
- docs/chapters/getting_started/troubleshooting.md
- docs/chapters/plantseg_interactive_napari/headless_batch_processing.md
- plantseg/viewer/headless.py
- plantseg/viewer/widget/predictions.py
- plantseg/viewer/widget/utils.py
With this PR, I make `--headless` mode handle a special case: a workflow of "open file -> multi-channel network prediction -> export file". A workflow combined with any post-processing step may still fail. Multi-channel output from networks were not handled until #184. Back then, `--headless` mode with DAG was not considered as an important use case, because 
1. I made `--config` mode available for processing multi-channel network output;
2. Lorenzo will refactor headless mode with a new design.
> Headless: Handle multi-channel prediction output and add docs

- conda-recipe/meta.yaml
- environment-dev.yaml
- environment.yaml
- plantseg/models/__init__.py
- plantseg/models/zoo.py
- plantseg/predictions/functional/predictions.py
- plantseg/viewer/widget/predictions.py
- tests/test_bioimageio.py
After Zenodo failed BioImage.IO and BioImage.IO's storage moved to EBI, this PR:
- is the first attempt for https://github.com/kreshuklab/plant-seg/issues/210
- makes prediction with models from BioImage.IO Model Zoo possible
- limited to PlantSeg-compatible models, i.e. `UNet3D`s and `UNet2D`s trained with `pytorch-3dunet`
- depend on `bioimageio.core` package now, but conda has no "extra"s like pip so it's made compulsory
The next step is to discuss with BioImage.IO team about filtering models and make PlantSeg community partner.
Prediction with PlantSeg Custom/Official models in PlantSeg Zoo is not affected:
> BioImage.IO Core: Execute PlantSeg-compatible models by nickname

- plantseg/segmentation/functional/segmentation.py
- plantseg/viewer/widget/dataprocessing.py
- plantseg/viewer/widget/segmentation.py
This PR originally attempts to fix the type warnings from #249. There are two modules using `Enum` for choices. I have enhanced both and resolved the type warnings along the way. The most significant changes include:
```python
class RescaleType(Enum):
NEAREST = (0, "Nearest")
LINEAR = (1, "Linear")
BILINEAR = (2, "Bilinear")
def __init__(self, int_val, str_val):
self.int_val = int_val
self.str_val = str_val
@classmethod
def to_choices(cls):
return [(mode.str_val, mode.int_val) for mode in cls]
class RescaleModes(Enum):
FROM_FACTOR = "From factor"
TO_LAYER_VOXEL_SIZE = "To layer voxel size"
TO_LAYER_SHAPE = "To layer shape"
TO_MODEL_VOXEL_SIZE = "To model voxel size"
TO_VOXEL_SIZE = "To voxel size"
SET_SHAPE = "To shape"
SET_VOXEL_SIZE = "Set voxel size"
@classmethod
def to_choices(cls): …
```
> Improve use of `Enum` as widget choices and fix types

- .gitignore
- plantseg/models/zoo.py
- plantseg/viewer/widget/predictions.py
- tests/test_bioimageio.py
This PR provides users a theoretical minimum halo for U-Nets, but in practice a smaller halo may also work well.
This PR attempts to fix #251 
Reference: [Exact Tile-Based Segmentation Inference for Images Larger than GPU Memory](https://doi.org/10.6028/jres.126.009)
> Recommend users a halo for U-Nets

- plantseg/viewer/widget/predictions.py
- tests/test_model_zoo.py
- Fix #261 
```python
$ pytest
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.2.1, pluggy-1.5.0
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8
rootdir: /g/kreshuk/yu/repositories/plant-seg-doc
plugins: napari-plugin-engine-0.2.0, npe2-0.7.5, napari-0.4.19.post1, anyio-4.2.0, qt-4.4.0, xdist-3.5.0
collected 32 items                                                             
tests/test_bioimageio.py ...                                             [  9%]
tests/test_data_processing.py ........                                   [ 34%]
tests/test_io_zarr.py .....                                              [ 50%]
tests/test_model.py ...                                                  [ 59%] …
```
> Test: Fix always-skipped test and misleading name

- .bumpversion.cfg
- environment-dev.yaml
- pyproject.toml
- `bumpversion` and `bump2version` are both no longer maintained. Switch to _Bump My Version_.
- surprisingly I can now combine `.bumpversion.toml` into `pyproject.toml`
- manually delete tags `v.1.0.0` and `v1.0.0`, and create `1.0.0` 
- also I just became aware of _Conventional Commits_
```shell
$ git show-ref --tags
d3fa7165e780683b4daf4ed9bc12bce83ad80252 refs/tags/1.0.1
b304df5d35e725391caf27e4f7c174e2a306f65d refs/tags/1.0.10
fac3a535e7c6cda2798db8746caf6e1f114e44db refs/tags/1.0.2
e18e885927315726ad0bba96d5e4342e33cf1d35 refs/tags/1.0.3
90a6db743529b662f0d67997a21202db7542599f refs/tags/1.0.4
...
...
68b51f9d77ead006aa5db95bfd3599e3cd24ff0b refs/tags/1.7.0
49ced6ae075bfa62c1ad6ef08683723504baf7de refs/tags/1.7.1
c44082c8360bdec85a1ec3beb9b053b6bb5a5ba5 refs/tags/1.8.0 …
```
> chore: migrate from `bumpversion` to `bump-my-version`

- .github/workflows/build-deploy-book.yml
- docs/snippets/napari_widgets_render.py
This PR fixes a rabbit-hole issue that I encountered when trying to run the PlantSeg documentation build. 
Qt wasn't able to find the icons napari build.
```pytb
WARNING: Cannot open file '/yu/repositories/plant-seg/theme_light:/minus_50.svg', because: No such file or directory
WARNING:vispy:Cannot open file '/yu/repositories/plant-seg/theme_light:/minus_50.svg', because: No such file or directory
WARNING: Cannot open file '/yu/repositories/plant-seg/theme_dark:/drop_down_50.svg', because: No such file or directory
WARNING:vispy:Cannot open file '/yu/repositories/plant-seg/theme_dark:/drop_down_50.svg', because: No such file or directory
WARNING: Cannot open file '/yu/repositories/plant-seg/theme_dark:/plus_50.svg', because: No such file or directory
WARNING:vispy:Cannot open file …
```
> fix(docs): teach Qt to find napari icons

- docs/chapters/getting_started/installation.md
- plantseg/run_plantseg.py
Fix #274.
Try to improve error message for users to deal with `KeyError` introduced by upgrade.
Maybe we can also just delete the folders for them? @lorenzocerrone
> fix(installation): remove old configs if `KeyError` | macOS installation

- plantseg/__init__.py
I was able to reproduce this in the plantseg env (but not in a clean env) 
The issue is the order of import of numpy/torch, and the fact that we are reading the state dict from file. 
```python
import numpy as np
import torch
model = torch.nn.Conv3d(64, 32, kernel_size=(3, 3, 3))
torch.save(model.state_dict(), "model.pth")
model.load_state_dict(torch.load("model.pth"))
```
```python
import torch
import numpy as np
model = torch.nn.Conv3d(64, 32, kernel_size=(3, 3, 3))
torch.save(model.state_dict(), "model.pth")
model.load_state_dict(torch.load("model.pth"))
```
```python
import numpy as np
import torch
model = torch.nn.Conv3d(64, 32, kernel_size=(3, 3, 3))
state_dict = model.state_dict()
model.load_state_dict(state_dict)
```
For now importing `torch` in the `__init__.py` works and has no …
> fixes PlantSeg crash on apple silicon #273

- docs/index.md
- plantseg/predictions/functional/array_predictor.py
This PR addresses an issue where users had to restart PlantSeg to recover from out-of-memory (OOM) errors when the combined patch size and patch halo exceed the device's memory capacity. Now VRAM is freed properly.
> feat(pred): check and free VRAM for prediction with oversized patch 

- plantseg/core/image.py
- plantseg/core/voxelsize.py
- plantseg/viewer_napari/widgets/io.py
- tests/core/test_image.py
- tests/core/test_voxelsize.py
- tests/io/test_io.py
This PR fixes two things:
1. `voxel_size.voxel_size` has been used to get the actual tuple, which is not neat. Now one either uses it directly and let the `__len__`, `__iter__`, and `__array__` handle `None`; or it can be turned into tuple by builtin `tuple()` 
2. There has been an `.is_valid` property, which doesn't really work with type checkers and is almost not used at all. I safely removed it in favour of checking `None` directly.
> Make VoxelSize iterable and array-like, remove `.is_valid`

- plantseg/viewer_napari/widgets/predictions.py
This is perhaps the first use case of `magicgui.types.Separator` because I created it for this : )
> refactor: use `magicgui.types.Separator`

- conda-recipe/meta.yaml
- plantseg/functionals/segmentation/segmentation.py
- plantseg/tasks/segmentation_tasks.py
- plantseg/viewer_napari/containers.py
- plantseg/viewer_napari/widgets/__init__.py
- plantseg/viewer_napari/widgets/prediction.py
- plantseg/viewer_napari/widgets/segmentation.py
This PR fixes the semantic type and data type errors for lifted multicut, and integrate it into agglomeration widget:
GASP:
LMC:
> Fix and integrate lifted multicut widget into agglomeration widget

- plantseg/functionals/dataprocessing/labelprocessing.py
- plantseg/tasks/dataprocessing_tasks.py
- plantseg/viewer_napari/containers.py
- plantseg/viewer_napari/widgets/__init__.py
- plantseg/viewer_napari/widgets/dataprocessing.py
- tests/functionals/dataprocessing/test_labelprocessing.py
> Refactor and recover widgets: cropping and label processing

- plantseg/core/image.py
- plantseg/io/h5.py
- plantseg/io/zarr.py
- tests/io/test_io.py
- tests/tasks/test_io_tasks.py
- fix #334 
- fix similar bug in export zarr
- add key check when exporting zarr/h5 to avoid hard to parse errors
- add task io testing
> fix h5 export

- .github/workflows/build-and-test-package.yml
- conda-recipe/meta.yaml
- docs/chapters/getting_started/installation.md
- environment-elife.yml
- environment.yaml
- setup.py
This PR fixes two problems:
1. Conda recipe on conda-forge is different from plantseg repo.
2. Plantseg logo was not even included into the package. It was only showing on dev env where the repo exists.
> Match conda recipe and include `package_data` logo

- plantseg/core/image.py
- plantseg/io/h5.py
- plantseg/tasks/dataprocessing_tasks.py
- plantseg/tasks/io_tasks.py
- plantseg/viewer_napari/containers.py
- plantseg/viewer_napari/viewer.py
- plantseg/viewer_napari/widgets/__init__.py
- plantseg/viewer_napari/widgets/dataprocessing.py
- plantseg/viewer_napari/widgets/io.py
- plantseg/viewer_napari/widgets/prediction.py
- plantseg/viewer_napari/widgets/proofreading.py
- plantseg/viewer_napari/widgets/segmentation.py
- plantseg/viewer_napari/widgets/utils.py
- tests/headless/test_headless.py
- tests/tasks/test_io_tasks.py
- tests/tasks/test_prediction_tasks.py
Unrelated changes:
@qin-yu test it a bit and let me know if the behavior did not change
> Proofreading improvements

- plantseg/functionals/prediction/utils/size_finder.py
- tests/functionals/prediction/test_size_finder.py
This PR attempts to fix #358.
1. `find_batch_size()` now catches and handles all runtime errors during probing.  
2. A specific issue, where VRAM is sufficient but the layer can only support `INT_MAX` elements, is tested.
> fix: allow more runtime errors in `find_batch_size()`

- docs/chapters/getting_started/index.md
- docs/chapters/getting_started/installation.md
- docs/chapters/plantseg_legacy/installation.md
- docs/chapters/python_api/functionals/index.md
- mkdocs.yml
Together with 32e615985c540023e12a6da1df44a692c1cec7fa and d031d78f1fb075f49988c34fd4726fa19d4f01d1, this PR should fix #350.
> docs: PlantSeg v1 installation guide

- plantseg/core/image.py
- plantseg/headless/headless.py
- plantseg/io/h5.py
- plantseg/io/io.py
- plantseg/viewer_napari/widgets/io.py
- plantseg/viewer_napari/widgets/proofreading.py
Adeleh from University of Potsdam sent me email about PlantSeg can't open her .JPG and .TIF files. This PR improves the extension checking throughout PlantSeg and makes `smart_load()`s consistent.
> Fix smart load | Make extension check case-insensitive

- plantseg/functionals/prediction/prediction.py
From this
```python
2025-01-24 16:29:51.676 | INFO     | bioimageio.spec._internal.io_utils:open_bioimageio_yaml:131 - loading philosophical-panda from https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/philosophical-panda/0.0.11/files/rdf.yaml
Downloading data from 'https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/philosophical-panda/0.0.11/files/rdf.yaml' to file '/home/runner/.cache/bioimageio/520a69782c7dafb6478e43ebcc4679b0-rdf.yaml'.
Downloading data from 'https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/philosophical-panda/0.0.11/files/README.md' to file '/home/runner/.cache/bioimageio/42620dae3e3850cefbf0475c7cf590dd-README.md'.
SHA256 hash of downloaded file: fc6e1292ca309bedaca504260cecc9a7bc9f26e9328eb7a051f82a2ceec475e3
Use this value as the …
```
> Avoid BioImage.IO Core downloading everything from model zoo entries

- .github/workflows/build-and-publish-docs.yml
Default conda is now v25.1 and the release version can no longer be `"DOC_RELEASE"`.
> fix(ci): fix Found invalid version predicate in "DOC_RELEASE"

- .github/workflows/build-and-publish-docs.yml
- conda-recipe/meta.yaml
- environment-dev-apple.yaml
- environment-dev.yaml
- environment.yaml
Pin `xarray` to avoid breaking changes in ops module
Recent breaking changes in the `xarray.ops` module are not yet handled by `bioimageio.core`, which then breaks documentation screenshots and causes confusion for new users. To prevent this, we now pin `xarray` to `<2025.3.0` until upstream compatibility is restored.
Related: 
- #396
> build: pin xarray due to #396

- .github/workflows/release.yml
Workflow is manually triggered to bumb the version, make a tag, and make a github release, including a changelog.
> ci: add workflow for release

- .github/workflows/conventional-commit.yml
Just squash-merged a PR but forgot to conventional commit it T_T... Adding a CI to force me remembering. This PR adds a CI that checks the PR title, so the default commit message for squash merge will be valid. Reference: [here](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
Named it differently than `ci: add commitlint workflow for PR title enforcement` to test.
> ci: add commitlint workflow for PR title enforcement

- conda-recipe/meta.yaml
- environment-dev-apple.yaml
- environment-dev.yaml
- environment.yaml
- #396 
- has been fixed since release v0.8.0 of biomageio.core
- https://github.com/bioimage-io/spec-bioimage-io/issues/663 
- has been fixed since release [v2.11.0](https://github.com/pydantic/pydantic/releases/tag/v2.11.0) of Pydantic ([#11008](https://github.com/pydantic/pydantic/pull/11008))
> build: lift `xarray` and `pydantic` restrictions

- plantseg/viewer_napari/viewer.py
- plantseg/viewer_napari/widgets/dataprocessing.py
- plantseg/viewer_napari/widgets/io.py
- plantseg/viewer_napari/widgets/prediction.py
- plantseg/viewer_napari/widgets/segmentation.py
fixes #198 
This implements updates to all layer drop-down menus on selecting a layer.  
Not the most ideal variant, but triggering on name-change would require a code change everywhere where a layer is created, which would become messy quickly.
> fix: update layer names after renaming

- .github/workflows/release.yml
The installer name and displayed version in the installer lags one version behind as the git repo state before the gh-action got pulled.
> fix: release version name lagging behind

- plantseg/viewer_napari/widgets/utils.py
This PR fixes the syntax complained by #454: `Cannot use an escape sequence (backslash) in f-strings on Python 3.11 (syntax was added in Python 3.12)`
> fix: escape sequence (backslash) in f-strings

- plantseg/viewer_napari/widgets/segmentation.py
- tests/widgets/test_segmentation.py
This PR fixes the wrong default behaviour of agglomeration widget introduced in #450 where the raw image is used as the boundary reference image.
This is simply fixing the default behaviour, but more needs to be done for #458
> fix: default input for agglomeration should be boundary prediction

- plantseg/viewer_napari/widgets/segmentation.py
- tests/widgets/test_segmentation.py
This allows the selection of not only raw images, but also predictions and segmentations as the nuclei image for lmc.
Addresses parts of #458
> fix: allow nuclei images to be raw, prediction, or segmentation

- plantseg/viewer_napari/widgets/proofreading.py
- tests/widgets/test_proofreading.py
Proofreading uses threads to not lock up the GUI, but the locking mechanism was broken.
fixes #462
> fix: lock now correctly working across threads

- .github/workflows/release.yml
Codecov comparison is not working due to `Missing Base Commit` Maybe branching only from tested commits fixes this.
> ci: upload to codecov during release
